spring:
  profiles:
    active: h2
  application:
    name: liquibase
server:
  servlet:
    context-path: /liquibase

logging:
  level:
    "liquibase": info
---
spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?current_schema=public
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    parameters:
      textColumnType: TEXT
    contexts: nonprod
---
spring:
  profiles: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:postgres
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres
  liquibase:
    parameters:
      textColumnType: VARCHAR(250)
    contexts: nonprod
  h2:
    console:
      enabled: true